=== feralito4/Extreventos/patterns/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Declaration -->

	<!-- Elements -->
	<xs:element name="page" type="pageType"/>
	
	<xs:element name="selectorUnit">
		<xs:complexType>
			<xs:attributeGroup ref="stdUnitAttributes"/>
			<xs:attribute name="type">
				<xs:simpleType>
				 	<xs:restriction base="xs:token">
				   		<xs:enumeration value="keyCondition"/>
				   		<xs:enumeration value="roleCondition"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parentId" type="xs:token"/>
		</xs:complexType>
	</xs:element>

	<xs:group name="contentUnits">
		<xs:choice>
   			<xs:element name="powerIndexUnit" type="stdUnitAttributesType"/>
   			<xs:element name="dataUnit" type="stdUnitAttributesType"/>
   			<xs:element name="entryUnit">
				<xs:complexType>
					<xs:attributeGroup ref="stdUnitAttributes"/>
					<xs:attribute name="type">
						<xs:simpleType>
						 	<xs:restriction base="xs:token">
						   		<xs:enumeration value="preloaded"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
   			<xs:element name="multiMessageUnit" type="stdUnitAttributesType"/>
   			<xs:element name="noOpContentUnit" type="stdUnitAttributesType"/>
   			<xs:element ref="selectorUnit"/>
		</xs:choice>
	</xs:group>

	<xs:group name="links">
		<xs:choice>
   			<xs:element name="okLink" type="okKoType"/>
   			<xs:element name="koLink" type="okKoType"/>
   			<xs:element name="normalNavigationFlow">
   				<xs:complexType>
					<xs:attributeGroup ref="stdLinkAttributes"/>
					<xs:attribute name="validate" type="xs:boolean"/>
					<xs:attribute name="type">
						<xs:simpleType>
						 	<xs:restriction base="xs:token">
						   		<xs:enumeration value="isNotNull"/>
						    	<xs:enumeration value="fixedValue"/>
						   		<xs:enumeration value="entryToCreate"/>
						   		<xs:enumeration value="entryToUpdate"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
   			<xs:element name="dataFlow">
   				<xs:complexType>
					<xs:attributeGroup ref="stdLinkAttributes"/>
					<xs:attribute name="type">
						<xs:simpleType>
						 	<xs:restriction base="xs:token">
						    	<xs:enumeration value="preload"/>
						    	<xs:enumeration value="entryToConnect"/>
						    	<xs:enumeration value="entryToReconnect"/>
						    	<xs:enumeration value="unitToEntry"/>
						    	<xs:enumeration value="unitToEntryRole"/>
						   		<xs:enumeration value="entryToCreate"/>
						   		<xs:enumeration value="entryToUpdate"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>

	<!-- Attributes -->

	<xs:attribute name="id">    
		<xs:simpleType>
	        <xs:restriction base="xs:token">
	            <xs:minLength value="1"/>
	        </xs:restriction>
	    </xs:simpleType>
	</xs:attribute>
	<xs:attribute name="name" type="xs:token"/>

	<!-- AttributeGroups -->
	<xs:attributeGroup name="stdLinkAttributes">
		<xs:attribute ref="id" use="required"/>
		<xs:attribute ref="name"/>
		<xs:attribute name="sourceId" type="xs:token" use="required"/>
		<xs:attribute name="targetId" type="xs:token" use="required"/>
	</xs:attributeGroup>

	<xs:attributeGroup name="stdUnitAttributes">
		<xs:attribute ref="id" use="required"/>
		<xs:attribute ref="name"/>
		<xs:attributeGroup ref="coordinates"/>
	</xs:attributeGroup>

	<xs:attributeGroup name="coordinates">
		<xs:attribute name="x" type="xs:token" use="required"/>
		<xs:attribute name="y" type="xs:token" use="required"/>
	</xs:attributeGroup>

	<!-- Complex types -->
	<xs:complexType name="stdUnitAttributesType">
		<xs:attributeGroup ref="stdUnitAttributes"/>
	</xs:complexType>

	<xs:complexType name="stdLinkAttributesType">
		<xs:attributeGroup ref="stdLinkAttributes"/>
	</xs:complexType>

	<xs:complexType name="pagesSectionType">
		<xs:sequence>
   			<xs:element ref="page" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="pageType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
   			<xs:element ref="page"/>
   			<xs:element name="xor" type="xorType"/>
			<xs:group ref="contentUnits"/>
		</xs:choice>
		<xs:attributeGroup ref="stdUnitAttributes"/>
		<xs:attribute name="landmark" type="xs:boolean"/>
		<xs:attribute name="default" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="xorType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
   			<xs:element ref="page"/>
			<xs:group ref="contentUnits"/>
		</xs:choice>
		<xs:attributeGroup ref="stdUnitAttributes"/>
	</xs:complexType>

	<xs:complexType name="outsideunitsType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
   			<xs:element name="createUnit" type="stdUnitAttributesType"/>
   			<xs:element name="deleteUnit" type="stdUnitAttributesType"/>
   			<xs:element name="updateUnit" type="stdUnitAttributesType"/>
   			<xs:element name="isNotNullUnit" type="stdUnitAttributesType"/>
   			<xs:element ref="selectorUnit"/>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="okKoType">
		<xs:attributeGroup ref="stdLinkAttributes"/>
		<xs:attribute name="message" type="xs:string"/>
		<xs:attribute name="type">
			<xs:simpleType>
			 	<xs:restriction base="xs:token">
			   		<xs:enumeration value="noCoupling"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="linksType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:group ref="links"/>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="relSubsectionType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:group ref="links"/>
			<xs:element ref="selectorUnit"/>
   			<xs:element name="connectUnit" type="stdUnitAttributesType"/>
   			<xs:element name="disconnectUnit" type="stdUnitAttributesType"/>
   			<xs:element name="reconnectUnit" type="stdUnitAttributesType"/>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="relationsType">
		<xs:sequence>
			<xs:element name="ALL" type="relSubsectionType" minOccurs="0"/>
			<xs:element name="LAST" type="linksType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="nmrelationsType">
		<xs:sequence>
			<xs:element name="ALL" type="relSubsectionType" minOccurs="0"/>
			<xs:element name="FIRST" type="linksType" minOccurs="0"/>
			<xs:element name="REMAINING" type="linksType" minOccurs="0"/>
			<xs:element name="LAST" type="linksType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

<!-- Root definition -->

	<xs:element name="PATTERN">	
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PAGES" type="pagesSectionType" minOccurs="0"/>
				<xs:element name="OUTSIDEUNITS" type="outsideunitsType" minOccurs="0"/>
				<xs:element name="LINKS" type="linksType" minOccurs="0"/>
				<xs:element name="RELATIONS" type="relationsType" minOccurs="0"/>
				<xs:element name="NMRELATIONS" type="nmrelationsType" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute ref="id" use="required"/>
			<xs:attribute ref="name" use="required"/>
		</xs:complexType>

		<xs:unique name="uniqueID">
			<xs:selector xpath=".//*" />
			<xs:field xpath="@id" />
		</xs:unique>
	</xs:element>

</xs:schema>

=== feralito4/Extreventos/DBScripts/patterns/Create (default).xml
<?xml version="1.0"?>

<PATTERN id="p1" name="Create (default)"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:noNamespaceSchemaLocation="schema.xsd">
	
	<!-- PAGES SECTION-->
	<PAGES>
		<page id="CreatePage" name="Create Page" landmark="true" x="30" y="30">
			<entryUnit id="entryUnit" name="EntryUnit" x="150" y="0"/>
			<multiMessageUnit id="multiMessageUnit" name="MultiMessageUnit" x="150" y="100"/>
		</page>
	</PAGES>		


	<!-- UNITS OUTSIDE OF ANY PAGE -->
	<OUTSIDEUNITS>
		<createUnit id="createUnit" name="CreateUnit" x="450" y="30"/>
	</OUTSIDEUNITS>


	<!-- LINKS SECTION -->
	<LINKS>
		<normalNavigationFlow id="nnfLoad" name="Load" sourceId="entryUnit" targetId="createUnit" type="entryToCreate"/>
		<koLink id="koCreate" sourceId="createUnit" targetId="multiMessageUnit" message="Failed creating data"/>
	</LINKS>


	<!-- RELATIONS SECTION -->
	<RELATIONS> <!-- Common section for 1:1, 1:N and N:M relations -->
		<ALL> <!-- All relations -->
			<selectorUnit id="selector#" name="selector#" parentId="CreatePage" x="0" y="0#"/>
			<dataFlow id="flowSelectorForm#" name="Load" sourceId="selector#" targetId="entryUnit" type="preload"/>
		</ALL>

		<LAST> <!-- Last relation (used to close operations chain) -->
			<okLink id="okConnect" sourceId="createUnit" targetId="multiMessageUnit" message="Data created correctly"/>
		</LAST>
	</RELATIONS>

	<NMRELATIONS> <!-- Specific section only for N:M relations (Replaces RELATIONS)-->
		<ALL> <!-- All N:M relations -->
			<selectorUnit id="selector #" name="selector#" parentId="CreatePage" x="0" y="0#"/>
			<dataFlow id="flowSelectorForm #" name="Load" sourceId="selector #" targetId="entryUnit" type="preload"/>

			<connectUnit id="connect%" name="connect%" x="450" y="130%"/>
			<dataFlow id="flowFormConnect%" name="Load" sourceId="entryUnit" targetId="connect%" type="entryToConnect"/>

			<koLink id="koConnect%" sourceId="connect%" targetId="multiMessageUnit" message="Failed creating data"/>
		</ALL>

		<FIRST> <!-- First N:M relation (used to start operations chain) -->
			<okLink id="okFirstConnect%" sourceId="createUnit" targetId="connect%" message=""/>	
		</FIRST>

		<REMAINING> <!-- Second and subsequent N:M relations (used to continue operations chain) -->
			<okLink id="okConnect%" sourceId="connect%-1" targetId="connect%" message=""/>
		</REMAINING>

		<LAST> <!-- Last relation (used to close operations chain) -->
			<okLink id="okConnect%+1" sourceId="connect%" targetId="multiMessageUnit" message="Data created correctly"/>	
		</LAST>
	</NMRELATIONS>

</PATTERN>


	<!-- # = iterative number for each relation -->
	<!-- % = iterative number for each NM relation -->

=== feralito4/Extreventos/DBScripts/patterns/AllInOne (default).xml
<?xml version="1.0"?>

<PATTERN id="p0" name="AllInOne (default)"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:noNamespaceSchemaLocation="schema.xsd">
	
	<!-- PAGES SECTION-->
	<PAGES>
		<page id="CRUDPage" name="CRUDPage" landmark="true" x="30" y="30">
			<xor id="XORPage" name="Alternative" x="0" y="0">
				<page id="DefaultPage" name="DefaultPage" default="true" x="30" y="30">
					<noOpContentUnit id="noOpContentUnit" name="New" x="5" y="5"/>
					<multiMessageUnit id="multiMessageUnit" name="MultiMessageUnit" x="0" y="150"/>
					<powerIndexUnit id="powerIndexUnit" name="PowerIndexUnit" x="150" y="0"/>
				</page>

				<page id="DetailsPage" name="Details" landmark="true" x="400" y="5">
					<dataUnit id="dataUnit" name="DataUnit" x="0" y="0"/>					
				</page>

				<page id="FormPage" name="Form" landmark="true" x="5" y="300">
					<entryUnit id="entryUnit" name="EntryUnit" x="200" y="150"/>	
					<selectorUnit id="selectorEntity" name="Selector" type="keyCondition" x="100" y="5"/>			
				</page>
			</xor>
		</page>
	</PAGES>		


	<!-- UNITS OUTSIDE OF ANY PAGE -->
	<OUTSIDEUNITS>
		<createUnit id="createUnit" name="CreateUnit" x="700" y="500"/>
		<deleteUnit id="deleteUnit" name="DeleteUnit" x="700" y="300"/>
		<updateUnit id="updateUnit" name="UpdateUnit"  x="700" y="800"/>
		<isNotNullUnit id="isNotNullUnit" name="New ..." x="700" y="650"/>
	</OUTSIDEUNITS>


	<!-- LINKS SECTION -->
	<LINKS>
		<normalNavigationFlow id= "nnf1" name="Close" sourceId="dataUnit" targetId="multiMessageUnit"/>
		<normalNavigationFlow id= "nnf2" name="Cancel" sourceId="entryUnit" targetId="multiMessageUnit" validate="false"/>
		<normalNavigationFlow id= "nnf3" name="New" sourceId="noOpContentUnit" targetId="selectorEntity" type="fixedValue"/>
		<normalNavigationFlow id= "nnf4" name="View" sourceId="powerIndexUnit" targetId="dataUnit"/>
		<normalNavigationFlow id= "nnf5" name="Modify" sourceId="powerIndexUnit" targetId="selectorEntity"/>
		<normalNavigationFlow id= "nnf6" name="Delete" sourceId="powerIndexUnit" targetId="deleteUnit"/>
		<normalNavigationFlow id= "nnf7" name="Accept" sourceId="entryUnit" targetId="isNotNullUnit" type="isNotNull"/>

		<okLink id="okDelete" sourceId="deleteUnit" targetId="multiMessageUnit" message="Data deleted correctly"/>
		<okLink id="okNN" sourceId="isNotNullUnit" targetId="updateUnit"/>

		<koLink id="koDelete" sourceId="deleteUnit" targetId="multiMessageUnit" message="Failed deleting data"/>
		<koLink id="koCreate" sourceId="createUnit" targetId="multiMessageUnit" message="Failed creating data"/>
		<koLink id="koUpdate" sourceId="updateUnit" targetId="multiMessageUnit" message="Failed modifying data"/>
		<koLink id="koNN" sourceId="isNotNullUnit" targetId="createUnit"/>


		<dataFlow id="df1" name="Load" sourceId="selectorEntity" targetId="entryUnit" type="unitToEntry"/>
		<dataFlow id="df2" name="Load" sourceId="entryUnit" targetId="createUnit" type="entryToCreate"/>
		<dataFlow id="df3" name="Load" sourceId="entryUnit" targetId="updateUnit" type="entryToUpdate"/>
	</LINKS>


	<!-- RELATIONS SECTION -->
	<RELATIONS> <!-- Common section for 1:1, 1:N and N:M relations -->
		<ALL> <!-- All relations -->
			<selectorUnit id="selector#" name="selector#" parentId="FormPage" x="300#" y="0"/>
			<dataFlow id="flowSelectorForm#" name="Load" sourceId="selector#" targetId="entryUnit" type="preload"/>
		</ALL>

		<LAST> <!-- Last relation (used to close operations chain) -->
			<okLink id="okConnect" sourceId="createUnit" targetId="multiMessageUnit" message="Data created correctly"/>	
			<okLink id="okReconnect" sourceId="updateUnit" targetId="multiMessageUnit" message="Data modified correctly"/>
		</LAST>
	</RELATIONS>

	<NMRELATIONS> <!-- Specific section only for N:M relations (Replaces RELATIONS)-->
		<ALL> <!-- All N:M relations -->
			<selectorUnit id="selector-#" name="selector#" parentId="FormPage" x="300#" y="0"/>
			<dataFlow id="flowSelectorForm-#" name="Load" sourceId="selector-#" targetId="entryUnit" type="preload"/>
			
			<selectorUnit id="selectorNM%" name="selectorNM%" parentId="FormPage" type="roleCondition" x="0" y="130%"/>
			<dataFlow id="flowSelectSelect%" name="Load" sourceId="selectorEntity" targetId="selectorNM%"/>
			<dataFlow id="flowSelectEntry%" name="Load" sourceId="selectorNM%" targetId="entryUnit" type="unitToEntryRole"/>

			<connectUnit id="connect%" name="connect%" x="850%" y="500"/>
			<dataFlow id="flowFormConnect%" name="Load" sourceId="entryUnit" targetId="connect%" type="entryToConnect"/>
			<koLink id="koConnect%" sourceId="connect%" targetId="multiMessageUnit" message="Failed creating/modifying data"/>

			<reconnectUnit id="reconnect%" name="reconnect%" x="850%" y="800"/>
			<dataFlow id="flowFormReconnect%" name="Load" sourceId="entryUnit" targetId="reconnect%" type="entryToReconnect"/>
			<koLink id="koReconnect%" sourceId="reconnect%" targetId="multiMessageUnit" message="Failed modifying data"/>
		</ALL>

		<FIRST> <!-- First N:M relation (used to start operations chain) -->
			<okLink id="okFirstConnect%" sourceId="createUnit" targetId="connect%"/>	
			<okLink id="okFirstReconnect%" sourceId="updateUnit" targetId="reconnect%"/>	
		</FIRST>

		<REMAINING> <!-- Second and subsequent N:M relations (used to continue operations chain) -->
			<okLink id="okConnect%" sourceId="connect%-1" targetId="connect%"/>
			<okLink id="okReconnect%" sourceId="reconnect%-1" targetId="reconnect%"/>
		</REMAINING>

		<LAST> <!-- Last relation (used to close operations chain) -->
			<okLink id="okConnect%+1" sourceId="connect%" targetId="multiMessageUnit" message="Data created correctly"/>	
			<okLink id="okReconnect%+1" sourceId="reconnect%" targetId="multiMessageUnit" message="Data modified correctly"/>
		</LAST>
	</NMRELATIONS>

</PATTERN>


	<!-- # = iterative number for each relation -->
	<!-- % = iterative number for each NM relation -->

=== feralito4/Extreventos/DBScripts/patterns/Update (default).xml
<?xml version="1.0"?>

<PATTERN id="p3" name="Update (default)"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:noNamespaceSchemaLocation="schema.xsd">
	
	<!-- PAGES SECTION-->
	<PAGES>
		<page id="UpdatePage" name="Update Page" landmark="true" x="30" y="30">
			<entryUnit id="entryUnit" name="EntryUnit" type="preloaded" x="200" y="200"/>
			<powerIndexUnit id="powerIndexUnit" name="PowerIndexUnit" x="0" y="0"/>
			<multiMessageUnit id="multiMessageUnit" name="MultiMessageUnit" x="150" y="300"/>
			<selectorUnit id="selectorEntity" name="selector" type="keyCondition" x="200" y="0"/>
		</page>
	</PAGES>		


	<!-- UNITS OUTSIDE OF ANY PAGE -->
	<OUTSIDEUNITS>
		<updateUnit id="updateUnit" name="UpdateUnit"  x="500" y="170"/>
	</OUTSIDEUNITS>


	<!-- LINKS SECTION -->
	<LINKS>
		<normalNavigationFlow id="nnfUpdate" name="Modify" sourceId="powerIndexUnit" targetId="selectorEntity" />
		<normalNavigationFlow id="nnfEntryUpdate" name="Load" sourceId="entryUnit" targetId="updateUnit" type="entryToUpdate"/>
		<dataFlow id="dfSelectorEntry" name="Load" sourceId="selectorEntity" targetId="entryUnit" type="unitToEntry"/>
		<koLink id="koUpdate" sourceId="updateUnit" targetId="multiMessageUnit" message="Failed modifying data"/>
	</LINKS>


	<!-- RELATIONS SECTION -->
	<RELATIONS> <!-- Common section for 1:1, 1:N and N:M relations -->
		<ALL> <!-- All relations -->
			<selectorUnit id="selector#" name="selector#" parentId="UpdatePage" x="300#" y="0"/>
			<dataFlow id="flowSelectorForm#" name="Load" sourceId="selector#" targetId="entryUnit" type="preload"/>
		</ALL>

		<LAST> <!-- Last relation (used to close operations chain) -->
			<okLink id="okReconnect" sourceId="updateUnit" targetId="multiMessageUnit" message="Data modified correctly"/>	
		</LAST>
	</RELATIONS>

	<NMRELATIONS> <!-- Specific section only for N:M relations (Replaces RELATIONS)-->
		<ALL> <!-- All N:M relations -->
			<selectorUnit id="selector #" name="selector#" parentId="UpdatePage" x="300#" y="0"/>
			<dataFlow id="flowSelectorForm #" name="Load" sourceId="selector #" targetId="entryUnit" type="preload"/>

			<selectorUnit id="selectorNM%" name="selectorNM%" parentId="UpdatePage" type="roleCondition" x="0" y="150%"/>
			<dataFlow id="flowSelectSelect%" name="Load" sourceId="selectorEntity" targetId="selectorNM%"/>
			<dataFlow id="flowSelectEntry%" name="Load" sourceId="selectorNM%" targetId="entryUnit" type="unitToEntryRole"/>

			<reconnectUnit id="reconnect%" name="reconnect%" x="500" y="300%"/>
			<dataFlow id="flowFormReconnect%" name="Load" sourceId="entryUnit" targetId="reconnect%" type="entryToReconnect"/>
			<koLink id="koReconnect%" sourceId="reconnect%" targetId="multiMessageUnit" message="Failed modifying data"/>			
		</ALL>

		<FIRST> <!-- First N:M relation (used to start operations chain) -->
			<okLink id="okFirstReconnect%" sourceId="updateUnit" targetId="reconnect%" message=""/>
		</FIRST>

		<REMAINING> <!-- Second and subsequent N:M relations (used to continue operations chain) -->
			<okLink id="okReconnect%" sourceId="reconnect%-1" targetId="reconnect%" message=""/>
		</REMAINING>

		<LAST> <!-- Last relation (used to close operations chain) -->
			<okLink id="okReconnect%+1" sourceId="reconnect%" targetId="multiMessageUnit" message="Data modified correctly"/>
		</LAST>
	</NMRELATIONS>

</PATTERN>


	<!-- # = iterative number for each relation -->
	<!-- % = iterative number for each NM relation -->

=== feralito4/Extreventos/patterns/Delete (default).xml
<?xml version="1.0"?>

<PATTERN id="p4" name="Delete (default)"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:noNamespaceSchemaLocation="schema.xsd">
	
	<!-- PAGES SECTION-->
	<PAGES>
		<page id="DeletePage" name="Delete Page" landmark="true" x="30" y="30">
			<powerIndexUnit id="powerIndexUnit" name="PowerIndexUnit" x="0" y="0"/>
			<multiMessageUnit id="multiMessageUnit" name="MultiMessageUnit" x="0" y="100"/>
		</page>
	</PAGES>		


	<!-- UNITS OUTSIDE OF ANY PAGE -->
	<OUTSIDEUNITS>
		<deleteUnit id="deleteUnit" name="DeleteUnit" x="300" y="30"/>
	</OUTSIDEUNITS>


	<!-- LINKS SECTION -->
	<LINKS>
		<normalNavigationFlow id="nnfDelete" name="Delete" sourceId="powerIndexUnit" targetId="deleteUnit"/>
		<koLink id="koDelete" sourceId="deleteUnit" targetId="multiMessageUnit" message="Failed deleting data"/>
		<okLink id="okDelete" sourceId="deleteUnit" targetId="multiMessageUnit" message="Data deleted correctly"/>
	</LINKS>

</PATTERN>
